run:
  timeout: 10m
  issues-exit-code: 1
  tests: false
  build-tags:
    - integration

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 20
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 150

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - funlen
    - gocyclo
    - lll

issues:
  exclude-files:
    - ".*_test\\.go$"

  exclude-rules:
    - path: cmd/
      linters:
        - gomnd
    - linters:
        - lll
      source: "^//go:generate "
    - path: ".*test_utils\\.go$"
      linters:
        - unused
    - path: ".*_mock\\.go$"
      linters:
        - unused

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
